jobs:
  build-and-test-amd64:
    docker:
      - image: cimg/go:1.19.5
    steps:
      - checkout
      - restore_cache:
          keys:
            - amd64-go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Run tests
          command: |
            gotestsum --junitfile /tmp/test-results/s3cp.xml
      - run:
          name: build amd64
          command: |
            version="$(git rev-parse HEAD)-$(git rev-parse --abbrev-ref HEAD)"
            go build -o s3cp.amd64 -ldflags="-s -w -X main.Commit=$version" s3cp.go
      - save_cache:
          key: amd64-go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - store_artifacts:
          path: s3cp.amd64
          destination: s3cp.amd64
      - store_test_results:
          path: /tmp/test-results
workflows:
  version: 2
  ci:
    jobs:
      - build-and-test-amd64
